'use client';
/* eslint-disable @next/next/no-html-link-for-pages */

import { FormEvent, useState } from 'react';

type DocumentRow = { id: string; originalFilename: string; specialtyId?: string; sourceYear?: number; uploadedAt: string; status: string; processingError?: string };
const errorMessage = (value: unknown) => typeof value === 'object' && value !== null && 'error' in value && typeof value.error === 'string' ? value.error : 'Request failed.';
const isDocument = (value: unknown): value is DocumentRow => typeof value === 'object' && value !== null && 'id' in value && typeof value.id === 'string' && 'originalFilename' in value && typeof value.originalFilename === 'string' && 'status' in value && typeof value.status === 'string';
const extractionCount = (value: unknown) => typeof value === 'object' && value !== null && 'extracted' in value && typeof value.extracted === 'number' ? value.extracted : 0;
export default function KnowledgeAdmin() {
  const [token, setToken] = useState(''); const [documents, setDocuments] = useState<DocumentRow[]>([]); const [message, setMessage] = useState('Enter the administrator access key to view or upload knowledge files.'); const [loading, setLoading] = useState(false);
  async function load() { if (!token) return; setLoading(true); const response = await fetch('/api/admin/knowledge/documents', { headers: { 'x-admin-token': token } }); const body: unknown = await response.json(); setLoading(false); if (!response.ok || !Array.isArray(body) || !body.every(isDocument)) return setMessage(response.ok ? 'Invalid document response.' : errorMessage(body)); setDocuments(body); setMessage(`${body.length} document${body.length === 1 ? '' : 's'} in the knowledge pipeline.`); }
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const file = new FormData(formElement).get('file'); if (!(file instanceof File) || !file.name) return; setLoading(true); const form = new FormData(); form.set('file', file); const response = await fetch('/api/admin/knowledge/documents', { method: 'POST', headers: { 'x-admin-token': token }, body: form }); const body: unknown = await response.json(); setLoading(false); setMessage(response.ok ? `${file.name}: ${extractionCount(body)} candidates extracted and ready for review.` : errorMessage(body)); if (response.ok) { formElement.reset(); await load(); } }
  async function publish(id: string) { setLoading(true); const response = await fetch(`/api/admin/knowledge/documents/${id}/publish`, { method: 'POST', headers: { 'x-admin-token': token } }); const body: unknown = await response.json(); setLoading(false); setMessage(response.ok ? 'Published knowledge is now available to the OSCE repository.' : errorMessage(body)); if (response.ok) await load(); }
  return <main className="knowledge-admin"><header><a href="/">← Student simulator</a><div><span className="eyebrow">INTERNAL ONLY</span><h1>Knowledge<br/><em>pipeline.</em></h1></div></header><section className="admin-intro"><p>Original documents remain evidence. This workspace extracts structured candidates for review before anything can enter student OSCE stations.</p><label>Administrator access key<input type="password" value={token} onChange={(event) => setToken(event.target.value)} placeholder="Required to unlock upload" /></label></section><section className="upload-card"><div><span className="eyebrow">01 / UPLOAD</span><h2>Add historical OSCE material</h2><p>TXT, Markdown, DOCX or PDF · maximum 25 MB</p></div><form onSubmit={upload}><input name="file" type="file" accept=".txt,.md,.markdown,.docx,.pdf" disabled={!token || loading}/><button className="start" disabled={!token || loading}>{loading ? 'Processing…' : 'Upload & extract'} <span>→</span></button></form></section><section className="documents"><div className="section-title"><div><span className="eyebrow">02 / REVIEW & PUBLISH</span><h2>Documents</h2></div><button className="refresh" onClick={load} disabled={!token || loading}>Refresh</button></div><p className="status-message">{message}</p>{documents.length === 0 ? <div className="empty">No documents yet. Upload a clean historical recollection file to start the review pipeline.</div> : <div className="document-list">{documents.map((document) => <article key={document.id} className="document-row"><div><b>{document.originalFilename}</b><span>{document.specialtyId?.replaceAll('_', ' ') ?? 'Specialty unresolved'} · {document.sourceYear ?? 'Year unknown'}</span></div><span className={`document-status ${document.status.toLowerCase()}`}>{document.status.replaceAll('_', ' ')}</span>{document.processingError ? <small>{document.processingError}</small> : <div className="document-actions"><a className="publish" href={`/admin/knowledge/documents/${document.id}`}>Review candidates</a>{document.status !== 'PUBLISHED' && <button className="publish" disabled={loading} onClick={() => publish(document.id)}>Publish reviewed</button>}</div>}</article>)}</div>}</section><footer>Only approved or edited candidates are publishable. Original evidence remains immutable.</footer></main>;
}
