import { DB, ensureKnowledgeSchema, id } from '@/lib/knowledge/db';
import { logOperationalError } from '@/lib/operations';
type SelfScoreRequest = { examSessionId: string; sessionQuestionId: string; studentAnswer: string; correctness: 'CORRECT' | 'PARTIAL' | 'INCORRECT'; score: number };
export async function POST(request: Request) { try { await ensureKnowledgeSchema(); const body: unknown = await request.json(); if (!isSelfScoreRequest(body)) return Response.json({ error: 'INVALID_SELF_SCORE_REQUEST' }, { status: 400 }); const membership = await DB.prepare('SELECT sq.id FROM exam_session_questions sq JOIN exam_sessions s ON s.id = sq.session_id WHERE s.id = ? AND sq.id = ? AND s.status = \'ACTIVE\'').bind(body.examSessionId, body.sessionQuestionId).first<{ id: string }>(); if (!membership) return Response.json({ error: 'SESSION_QUESTION_INVALID' }, { status: 409 }); const inserted = await DB.prepare('INSERT INTO exam_session_answers (id, session_id, session_question_id, student_answer, scoring_mode, correctness, score, created_at) VALUES (?, ?, ?, ?, \'SELF\', ?, ?, ?) ON CONFLICT(session_id, session_question_id) DO NOTHING').bind(id(), body.examSessionId, body.sessionQuestionId, body.studentAnswer, body.correctness, scoreFor(body.correctness), new Date().toISOString()).run(); if (!inserted.meta.changes) return Response.json({ error: 'ALREADY_ANSWERED' }, { status: 409 }); return Response.json({ ok: true }); } catch (error) { logOperationalError('exam.self_score', error); return Response.json({ error: 'SELF_SCORE_UNAVAILABLE' }, { status: 503 }); } }
// The client declares correctness; the score is derived from it server-side.
// Accepting both let a client post CORRECT with score 0, or INCORRECT with
// score 1, leaving internally inconsistent rows in the results table.
function scoreFor(correctness: SelfScoreRequest['correctness']): number { return correctness === 'CORRECT' ? 1 : correctness === 'PARTIAL' ? 0.5 : 0; }
function isSelfScoreRequest(value: unknown): value is SelfScoreRequest { return typeof value === 'object' && value !== null && 'examSessionId' in value && typeof value.examSessionId === 'string' && 'sessionQuestionId' in value && typeof value.sessionQuestionId === 'string' && 'studentAnswer' in value && typeof value.studentAnswer === 'string' && 'correctness' in value && (value.correctness === 'CORRECT' || value.correctness === 'PARTIAL' || value.correctness === 'INCORRECT') && 'score' in value && typeof value.score === 'number' && value.score >= 0 && value.score <= 1; }
