import { randomUUID } from 'node:crypto';
import type { AuthSession, ContentItem } from '@sos/contracts';
import { buildApp, type App } from '../src/http/app.js';
import { queryOne, queryRows } from '../src/platform/db.js';

/**
 * Test helpers. `app.inject()` exercises the full HTTP stack — plugins,
 * validation, auth, error handling — without binding a socket.
 */

let app: App | null = null;

export async function getApp(): Promise<App> {
  if (!app) {
    app = await buildApp();
    await app.ready();
  }
  return app;
}

export async function closeApp(): Promise<void> {
  await app?.close();
  app = null;
}

export interface Cohort {
  universityId: string;
  collegeId: string;
  programId: string;
  stage5Id: string;
  stage4Id: string;
  academicYearId: string;
  courseIds: string[];
  topicIds: string[];
}

let cohort: Cohort | null = null;

/** Builds the seed hierarchy once and caches the ids the tests need. */
export async function ensureCohort(): Promise<Cohort> {
  if (cohort) return cohort;

  const university = await queryOne<{ id: string }>(
    `INSERT INTO universities (slug, name_ar, name_en)
     VALUES ('uob', 'جامعة بغداد', 'University of Baghdad')
     ON CONFLICT (slug) DO UPDATE SET name_en = EXCLUDED.name_en RETURNING id`,
  );
  const college = await queryOne<{ id: string }>(
    `INSERT INTO colleges (university_id, slug, name_ar, name_en)
     VALUES ($1, 'medicine', 'كلية الطب', 'College of Medicine')
     ON CONFLICT (university_id, slug) DO UPDATE SET name_en = EXCLUDED.name_en RETURNING id`,
    [university!.id],
  );
  const program = await queryOne<{ id: string }>(
    `INSERT INTO programs (college_id, slug, name_ar, name_en)
     VALUES ($1, 'mbchb', 'طب وجراحة', 'MBChB')
     ON CONFLICT (college_id, slug) DO UPDATE SET name_en = EXCLUDED.name_en RETURNING id`,
    [college!.id],
  );
  const stage5 = await queryOne<{ id: string }>(
    `INSERT INTO stages (program_id, ordinal, name_ar, name_en)
     VALUES ($1, 5, 'الخامسة', 'Stage 5')
     ON CONFLICT (program_id, ordinal) DO UPDATE SET name_en = EXCLUDED.name_en RETURNING id`,
    [program!.id],
  );
  const stage4 = await queryOne<{ id: string }>(
    `INSERT INTO stages (program_id, ordinal, name_ar, name_en)
     VALUES ($1, 4, 'الرابعة', 'Stage 4')
     ON CONFLICT (program_id, ordinal) DO UPDATE SET name_en = EXCLUDED.name_en RETURNING id`,
    [program!.id],
  );
  const year = await queryOne<{ id: string }>(
    `INSERT INTO academic_years (university_id, label, starts_on, ends_on, is_current)
     VALUES ($1, '2025/2026', '2025-10-01', '2026-07-01', true)
     ON CONFLICT (university_id, label) DO UPDATE SET is_current = true RETURNING id`,
    [university!.id],
  );
  const course = await queryOne<{ id: string }>(
    `INSERT INTO courses (program_id, stage_id, academic_year_id, slug, name_ar, name_en)
     VALUES ($1, $2, $3, 'pediatrics', 'طب الأطفال', 'Pediatrics')
     ON CONFLICT (program_id, stage_id, slug) DO UPDATE SET name_en = EXCLUDED.name_en RETURNING id`,
    [program!.id, stage5!.id, year!.id],
  );
  const subject = await queryOne<{ id: string }>(
    `INSERT INTO subjects (course_id, slug, name_ar, name_en)
     VALUES ($1, 'nephrology', 'الكلى', 'Nephrology')
     ON CONFLICT (course_id, slug) DO UPDATE SET name_en = EXCLUDED.name_en RETURNING id`,
    [course!.id],
  );
  /*
   * Three topics, not one.
   *
   * Phase 5 made Topic a navigation primitive and added topic-to-topic
   * relationships, and a co-tagging edge cannot be tested against a cohort with
   * a single topic. `ordinal` keeps the ordering stable so `topicIds[1]` means
   * the same thing on every run.
   */
  await queryOne(
    `INSERT INTO topics (subject_id, slug, name_ar, name_en, ordinal)
     VALUES
       ($1, 'nephrotic-syndrome',       'المتلازمة الكلوية',    'Nephrotic Syndrome', 0),
       ($1, 'acute-glomerulonephritis', 'التهاب الكبيبات الحاد', 'Acute Glomerulonephritis', 1),
       ($1, 'uti-in-children',          'التهاب المجاري البولية', 'UTI in Children', 2)
     ON CONFLICT (subject_id, slug) DO NOTHING`,
    [subject!.id],
  );
  const topics = await queryRows<{ id: string }>(`SELECT id FROM topics ORDER BY ordinal, slug`);

  cohort = {
    universityId: university!.id,
    collegeId: college!.id,
    programId: program!.id,
    stage5Id: stage5!.id,
    stage4Id: stage4!.id,
    academicYearId: year!.id,
    courseIds: [course!.id],
    topicIds: topics.map((t) => t.id),
  };
  return cohort;
}

/**
 * A token unique to this worker process.
 *
 * Vitest runs test files in parallel processes, and a module-level counter
 * starts at zero in every one of them — so `std_4_…` was generated by several
 * workers at once, leaving only a millisecond timestamp or a 1-in-100000 random
 * number to tell them apart. Across the hundreds of accounts this suite creates,
 * that collided often enough to fail CI on unrelated pull requests:
 *
 *   duplicate key value violates unique constraint "profiles_handle_key"
 *   DETAIL:  Key (lower(handle))=(std_12_18430) already exists.
 *
 * and whichever test lost the race reported it as "onboarding failed (409): That
 * handle is already taken" — which reads like a product defect rather than two
 * workers choosing the same name.
 *
 * The token makes uniqueness structural instead of probabilistic: two processes
 * cannot share one, and the counter separates calls within a process.
 */
const PROCESS_TOKEN = randomUUID().replace(/-/g, '').slice(0, 8);

let counter = 0;
export function uniqueEmail(prefix = 'student'): string {
  counter += 1;
  return `${prefix}-${PROCESS_TOKEN}-${counter}@uob.edu.iq`;
}

/**
 * A handle that is unique, and unique *early*.
 *
 * Both properties are load-bearing, and the obvious fix only had one. Putting
 * the process token first made every handle in a worker begin `std_b9e…`, and
 * the people-search test looks up `handle.slice(0, 6)` — so a search for the
 * first six characters matched every account the worker had made, the target
 * fell outside the ten results the endpoint returns, and a correct test failed.
 *
 * So the random part leads, which keeps a six-character prefix selective, and
 * the process token and counter trail it, which is what actually guarantees no
 * two calls anywhere can collide.
 */
export function uniqueHandle(prefix = 'std'): string {
  counter += 1;
  const lead = randomUUID().replace(/-/g, '').slice(0, 6);
  // Lower-case hex and underscores after a leading letter, so the result always
  // satisfies `handleSchema`.
  return `${prefix.slice(0, 1)}${lead}_${PROCESS_TOKEN}${counter}`.slice(0, 30);
}

export async function signupUser(password = 'correct-horse-battery'): Promise<AuthSession> {
  const app = await getApp();
  const response = await app.inject({
    method: 'POST',
    url: '/v1/auth/signup',
    payload: { email: uniqueEmail(), password, locale: 'ar' },
  });
  if (response.statusCode !== 201) {
    throw new Error(`signup failed (${response.statusCode}): ${response.body}`);
  }
  return response.json<AuthSession>();
}

/** Signs up a user and completes onboarding into the given stage. */
export async function onboardedUser(
  options: { stageId?: string } = {},
): Promise<{ session: AuthSession; handle: string }> {
  const app = await getApp();
  const c = await ensureCohort();
  const session = await signupUser();
  const handle = uniqueHandle();

  const response = await app.inject({
    method: 'POST',
    url: '/v1/me/onboarding',
    headers: { authorization: `Bearer ${session.tokens.accessToken}` },
    payload: {
      handle,
      displayName: 'Test Student',
      universityId: c.universityId,
      collegeId: c.collegeId,
      programId: c.programId,
      stageId: options.stageId ?? c.stage5Id,
      academicYearId: c.academicYearId,
      interestTopicIds: c.topicIds.slice(0, 1),
    },
  });
  if (response.statusCode !== 200) {
    throw new Error(`onboarding failed (${response.statusCode}): ${response.body}`);
  }
  return { session, handle };
}

export function auth(session: AuthSession): { authorization: string } {
  return { authorization: `Bearer ${session.tokens.accessToken}` };
}

// --- Phase 5c helpers -------------------------------------------------------

/**
 * Sets a user's global verification level directly.
 *
 * Direct SQL on purpose, and only for tests whose subject is something else.
 * The API path for this is `PUT /v1/admin/users/:id/verification` and it is
 * exercised properly in `authority.integration.test.ts` — including that it
 * refuses non-administrators and writes an audit row. Routing every classroom
 * fixture through an administrator login as well would triple the setup cost of
 * tests that are not about verification, and would make a failure in the admin
 * endpoint look like a failure in classrooms.
 */
export async function setVerificationLevel(
  userId: string,
  level: 'unverified' | 'student' | 'instructor' | 'official',
): Promise<void> {
  await queryOne(`UPDATE users SET verification_level = $2::verification_level WHERE id = $1 RETURNING id`, [
    userId,
    level,
  ]);
}

/**
 * An onboarded user who is also a verified instructor.
 *
 * The fixture most classroom tests need since Phase 5c: opening a classroom is
 * a teaching act, so an ordinary student can no longer set one up.
 */
export async function verifiedInstructor(
  options: { stageId?: string } = {},
): Promise<{ session: AuthSession; handle: string }> {
  const created = await onboardedUser(options);
  await setVerificationLevel(created.session.user.id, 'instructor');
  return created;
}

/**
 * An onboarded user who is a platform administrator.
 *
 * Direct SQL for the same structural reason the bootstrap script exists: only
 * an administrator can make an administrator, so the first one in any database
 * — including a test one — has to come from outside the API.
 */
export async function platformAdmin(): Promise<{ session: AuthSession; handle: string }> {
  const created = await onboardedUser();
  await queryOne(`UPDATE users SET role = 'admin' WHERE id = $1 RETURNING id`, [
    created.session.user.id,
  ]);
  return created;
}

// --- Phase 2 helpers --------------------------------------------------------

/**
 * A valid 1×1 PNG.
 *
 * Real bytes, not a stub: the upload path sniffs magic bytes and reads
 * dimensions from the IHDR chunk, so a placeholder would be rejected — which
 * is exactly what the tests are there to verify.
 */
export const TINY_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
  'base64',
);

/** Bytes that are not any image format, used to prove MIME sniffing works. */
export const NOT_AN_IMAGE = Buffer.from('#!/bin/sh\necho definitely not a png\n', 'utf8');

/** Builds a multipart body by hand — `inject` has no form-data helper. */
export function multipartBody(
  bytes: Buffer,
  filename: string,
  declaredMime: string,
): { payload: Buffer; headers: Record<string, string> } {
  const boundary = `----sosTest${Math.random().toString(36).slice(2)}`;
  const head = Buffer.from(
    `--${boundary}\r\n` +
      `Content-Disposition: form-data; name="file"; filename="${filename}"\r\n` +
      `Content-Type: ${declaredMime}\r\n\r\n`,
    'utf8',
  );
  const tail = Buffer.from(`\r\n--${boundary}--\r\n`, 'utf8');
  return {
    payload: Buffer.concat([head, bytes, tail]),
    headers: { 'content-type': `multipart/form-data; boundary=${boundary}` },
  };
}

export async function uploadImage(
  session: AuthSession,
  bytes: Buffer = TINY_PNG,
  filename = 'photo.png',
  declaredMime = 'image/png',
): Promise<{ statusCode: number; body: { id: string; url: string; width: number | null } }> {
  const app = await getApp();
  const { payload, headers } = multipartBody(bytes, filename, declaredMime);
  const response = await app.inject({
    method: 'POST',
    url: '/v1/files',
    headers: { ...headers, ...auth(session) },
    payload,
  });
  return {
    statusCode: response.statusCode,
    body: response.statusCode === 201 ? response.json() : { id: '', url: '', width: null },
  };
}

export async function createPost(
  session: AuthSession,
  payload: Record<string, unknown>,
): Promise<{ statusCode: number; body: ContentItem }> {
  const app = await getApp();
  const response = await app.inject({
    method: 'POST',
    url: '/v1/content',
    headers: auth(session),
    payload,
  });
  return { statusCode: response.statusCode, body: response.json() };
}

/**
 * Reads the feed for a visibility assertion.
 *
 * Defaults to `scope=recent`, NOT the ranked home feed, and the distinction
 * matters. Almost every caller is asking "can this reader see this content?" —
 * a permission question. The ranked scope answers a different one, and it
 * answers it against a shared test database that every suite writes into, so a
 * probe post can be pushed off the first page by content another test file
 * created. That failure looks like a leak and is not one.
 *
 * Both scopes run the identical permission predicate in `buildFeedQuery`, so
 * nothing about the security property is weakened by ordering deterministically
 * — the item under test is the newest, and therefore always on page one.
 *
 * Ranking has its own coverage in `feed-parity.integration.test.ts`, which is
 * where an ordering assertion belongs.
 */
export async function readFeed(
  session: AuthSession,
  query = '?scope=recent&limit=50',
): Promise<{ items: ContentItem[]; nextCursor: string | null }> {
  const app = await getApp();
  const response = await app.inject({
    method: 'GET',
    url: `/v1/feed${query}`,
    headers: auth(session),
  });
  if (response.statusCode !== 200) {
    throw new Error(`feed failed (${response.statusCode}): ${response.body}`);
  }
  return response.json();
}
