'use client';

import { useEffect, useMemo, useState } from 'react';

type Specialty = { id: string; english: string; arabic: string; icon: string; tone: string };
type Question = { id?: string; prompt: string; answer?: string; category: string; explanation?: string; evaluationReady?: boolean };
type ClinicalCase = { id?: string; title: string; scenario: string; questions: Question[] };
type Examiner = { id: string; name: string; specialtyId: string; cases: ClinicalCase[]; questions: number };
type EvaluationResult = { correctness: 'CORRECT'|'PARTIAL'|'INCORRECT'; score: number; coveredPoints: string[]; missingPoints: string[]; feedback: string; confidence: number };

const specialties: Specialty[] = [
  { id: 'internal', english: 'Internal Medicine', arabic: 'باطنية', icon: '✦', tone: 'indigo' },
  { id: 'pediatrics', english: 'Pediatrics', arabic: 'أطفال', icon: '◌', tone: 'sky' },
  { id: 'surgery', english: 'Surgery', arabic: 'جراحة', icon: '✚', tone: 'terracotta' },
  { id: 'minor', english: 'Minor Specialties', arabic: 'ماينورات', icon: '◒', tone: 'sage' },
  { id: 'obgyn', english: 'Obstetrics & Gynecology', arabic: 'نسائية', icon: '◈', tone: 'rose' },
];

const nephrotic: ClinicalCase = { title: 'Nephrotic Syndrome', scenario: 'A 6-year-old boy presents with generalized body swelling for five days. You are asked to take a focused history and discuss the patient with the examiner.', questions: [
  { prompt: 'What is the most likely diagnosis?', answer: 'Nephrotic syndrome — most commonly minimal change disease at this age.', category: 'Diagnosis' },
  { prompt: 'What key features would you ask about in the history?', answer: 'Onset and progression of edema, reduced urine output or frothy urine, recent infection, fever, abdominal pain, medication use, and symptoms of systemic disease.', category: 'History' },
  { prompt: 'What investigations would you request?', answer: 'Urinalysis and urine protein quantification, serum albumin, lipid profile, renal function, electrolytes, and a full blood count.', category: 'Investigation' },
  { prompt: 'What are the major complications?', answer: 'Infection, thrombosis, hypovolemia, and acute kidney injury.', category: 'Complications', explanation: 'Think of loss of immunoglobulins and anticoagulants, alongside intravascular depletion.' },
] };
const bronchiolitis: ClinicalCase = { title: 'Bronchiolitis', scenario: 'A 7-month-old infant is brought with two days of cough, poor feeding, and increasing work of breathing.', questions: [
  { prompt: 'What is your most likely diagnosis?', answer: 'Acute bronchiolitis, usually caused by a viral lower respiratory tract infection.', category: 'Diagnosis' },
  { prompt: 'What danger signs would make you admit this child?', answer: 'Apnea, hypoxia, severe respiratory distress, inability to feed or dehydration, exhaustion, or significant comorbidity.', category: 'Emergency' },
  { prompt: 'How is uncomplicated bronchiolitis managed?', answer: 'Supportive care: assess oxygenation and hydration, provide oxygen if needed, and support feeding. Antibiotics and routine bronchodilators are not indicated.', category: 'Management' },
] };
const examiners: Examiner[] = [
  { id: 'ahmed', name: 'Dr. Ahmed Al-Karim', specialtyId: 'pediatrics', cases: [nephrotic, bronchiolitis], questions: 86 },
  { id: 'hassan', name: 'Dr. Hassan Al-Mansouri', specialtyId: 'pediatrics', cases: [bronchiolitis], questions: 54 },
  { id: 'sara', name: 'Dr. Sara Al-Rawi', specialtyId: 'internal', cases: [nephrotic], questions: 71 },
  { id: 'omar', name: 'Dr. Omar Al-Hadithi', specialtyId: 'surgery', cases: [bronchiolitis], questions: 63 },
  { id: 'nour', name: 'Dr. Nour Al-Bayati', specialtyId: 'minor', cases: [nephrotic], questions: 42 },
  { id: 'rana', name: 'Dr. Rana Al-Samarrai', specialtyId: 'obgyn', cases: [nephrotic], questions: 68 },
];
const pick = <T,>(values: T[]) => values[Math.floor(Math.random() * values.length)];

export default function Home() {
  const [screen, setScreen] = useState<'splash'|'specialties'|'configure'|'reveal'|'prepare'|'question'|'results'>('splash');
  const [specialty, setSpecialty] = useState<Specialty | null>(null); const [mode, setMode] = useState<'random'|'choose'>('random');
  const [examiner, setExaminer] = useState<Examiner | null>(null); const [duration, setDuration] = useState(3); const [caseStudy, setCaseStudy] = useState<ClinicalCase | null>(null);
  const [seconds, setSeconds] = useState(180); const [preparationEndsAt, setPreparationEndsAt] = useState<number | null>(null); const [questionIndex, setQuestionIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [answer, setAnswer] = useState(''); const [scores, setScores] = useState<number[]>([]); const [scoreModes, setScoreModes] = useState<('AUTOMATIC'|'SELF')[]>([]); const [examSessionId, setExamSessionId] = useState<string | null>(null); const [sessionQuestionIds, setSessionQuestionIds] = useState<Record<string, string>>({}); const [evaluation, setEvaluation] = useState<EvaluationResult | null>(null); const [evaluationState, setEvaluationState] = useState<'idle'|'submitting'|'fallback'|'error'>('idle');
  const [publishedExaminers, setPublishedExaminers] = useState<Examiner[]>([]); const [loadingKnowledge, setLoadingKnowledge] = useState(false);
  const availableExaminers = useMemo(() => publishedExaminers.length ? publishedExaminers : examiners.filter((item) => item.specialtyId === specialty?.id), [publishedExaminers, specialty]); const currentQuestion = caseStudy?.questions[questionIndex];
  useEffect(() => { const timer = window.setTimeout(() => setScreen('specialties'), 1750); return () => clearTimeout(timer); }, []);
  useEffect(() => {
    if (screen !== 'prepare' || !preparationEndsAt) return;
    const timer = window.setInterval(() => {
      const remaining = Math.max(0, Math.ceil((preparationEndsAt - Date.now()) / 1000));
      setSeconds(remaining);
      if (remaining === 0) setScreen('question');
    }, 250);
    return () => clearInterval(timer);
  }, [screen, preparationEndsAt]);
  async function selectSpecialty(item: Specialty) { setSpecialty(item); setExaminer(null); setPublishedExaminers([]); setScreen('configure'); setLoadingKnowledge(true); try { const response = await fetch(`/api/knowledge/exam?specialtyId=${item.id === 'pediatrics' ? 'PEDIATRICS' : item.id === 'internal' ? 'INTERNAL_MEDICINE' : item.id === 'surgery' ? 'SURGERY' : item.id === 'minor' ? 'MINOR_SPECIALTIES' : 'OBSTETRICS_GYNECOLOGY'}`); const payload: unknown = await response.json(); if (response.ok && Array.isArray(payload)) setPublishedExaminers(payload.filter((value): value is Examiner => typeof value === 'object' && value !== null && 'id' in value && 'name' in value && 'cases' in value && 'questions' in value && typeof value.id === 'string' && typeof value.name === 'string' && Array.isArray(value.cases) && typeof value.questions === 'number').map((value) => ({ ...value, specialtyId: item.id }))); } finally { setLoadingKnowledge(false); } }
  async function beginExam() { const chosen = mode === 'random' ? pick(availableExaminers) : examiner; if (!chosen) return; const chosenCase = pick(chosen.cases); let sessionId: string | null = null; let questionIds: Record<string, string> = {}; if (specialty && chosenCase.id && chosenCase.questions.every((question) => question.id)) { try { const response = await fetch('/api/exam-sessions', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ specialtyId: specialty.id === 'pediatrics' ? 'PEDIATRICS' : specialty.id === 'internal' ? 'INTERNAL_MEDICINE' : specialty.id === 'surgery' ? 'SURGERY' : specialty.id === 'minor' ? 'MINOR_SPECIALTIES' : 'OBSTETRICS_GYNECOLOGY', examinerId: chosen.id, caseId: chosenCase.id }) }); const payload: unknown = await response.json(); if (response.ok && typeof payload === 'object' && payload !== null && 'examSessionId' in payload && typeof payload.examSessionId === 'string' && 'questions' in payload && Array.isArray(payload.questions)) { sessionId = payload.examSessionId; questionIds = Object.fromEntries(payload.questions.filter((item): item is { questionId:string; sessionQuestionId:string } => typeof item === 'object' && item !== null && 'questionId' in item && typeof item.questionId === 'string' && 'sessionQuestionId' in item && typeof item.sessionQuestionId === 'string').map((item) => [item.questionId, item.sessionQuestionId])); } } catch { /* Fixtures and unavailable local storage retain self-scoring. */ } } setExaminer(chosen); setCaseStudy(chosenCase); setExamSessionId(sessionId); setSessionQuestionIds(questionIds); setSeconds(duration * 60); setQuestionIndex(0); setScores([]); setScoreModes([]); setEvaluation(null); setEvaluationState('idle'); setRevealed(false); setAnswer(''); setScreen('reveal'); window.setTimeout(() => { setPreparationEndsAt(Date.now() + duration * 60_000); setScreen('prepare'); }, 1800); }
  async function submitEvaluation() { if (!currentQuestion?.id || !examSessionId || !sessionQuestionIds[currentQuestion.id]) { setEvaluationState('fallback'); setRevealed(true); return; } setEvaluationState('submitting'); try { const response = await fetch('/api/evaluate', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ examSessionId, sessionQuestionId: sessionQuestionIds[currentQuestion.id], studentAnswer: answer }) }); const payload: unknown = await response.json(); if (response.ok && typeof payload === 'object' && payload !== null && 'correctness' in payload && (payload.correctness === 'CORRECT' || payload.correctness === 'PARTIAL' || payload.correctness === 'INCORRECT') && 'score' in payload && typeof payload.score === 'number' && 'coveredPoints' in payload && Array.isArray(payload.coveredPoints) && 'missingPoints' in payload && Array.isArray(payload.missingPoints) && 'feedback' in payload && typeof payload.feedback === 'string' && 'confidence' in payload && typeof payload.confidence === 'number') { setEvaluation(payload as EvaluationResult); setRevealed(true); return; } if (response.status === 409 && typeof payload === 'object' && payload !== null && 'error' in payload && payload.error === 'AI_EVALUATION_UNAVAILABLE') { setEvaluationState('fallback'); setRevealed(true); return; } setEvaluationState('error'); } catch { setEvaluationState('error'); } }
  function grade(score: number, scoringMode: 'AUTOMATIC'|'SELF' = 'SELF') { const updated = [...scores, score]; if (!caseStudy) return; if (scoringMode === 'SELF' && examSessionId && currentQuestion?.id && sessionQuestionIds[currentQuestion.id]) void fetch('/api/exam-sessions/answers', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ examSessionId, sessionQuestionId: sessionQuestionIds[currentQuestion.id], studentAnswer: answer, correctness: score === 2 ? 'CORRECT' : score === 1 ? 'PARTIAL' : 'INCORRECT', score: score / 2 }) }); if (questionIndex + 1 >= caseStudy.questions.length) { setScores(updated); setScoreModes((items) => [...items, scoringMode]); setScreen('results'); return; } setScores(updated); setScoreModes((items) => [...items, scoringMode]); setQuestionIndex((value) => value + 1); setRevealed(false); setAnswer(''); setEvaluation(null); setEvaluationState('idle'); }
  const scorePercent = scores.length ? Math.round((scores.reduce((sum, item) => sum + item, 0) / (scores.length * 2)) * 100) : 0; const time = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`;
  return <main className="app-shell">
    {screen === 'splash' && <section className="splash"><div className="splash-mark">✚</div><p>OSCE</p><span>CLINICAL EXAMINATION SIMULATOR</span></section>}
    {screen === 'specialties' && <section className="home fade-in"><header className="topbar"><div className="brand"><i>✚</i><span>OSCE</span></div><p>Clinical examination simulator</p></header><div className="intro"><span className="eyebrow">FINAL-YEAR CLINICAL PRACTICE</span><h1>Step into the<br/><em>station.</em></h1><p>Practice the questions, cases, and examiner patterns that shape the real OSCE experience.</p></div><div className="specialty-grid">{specialties.map((item, index) => <button key={item.id} className={`specialty-card ${item.tone}`} style={{ animationDelay: `${index * 55}ms` }} onClick={() => selectSpecialty(item)}><span className="card-icon">{item.icon}</span><span className="arabic" dir="rtl">{item.arabic}</span><strong>{item.english}</strong><span className="arrow">↗</span></button>)}</div><footer>Built around examiner-associated historical cases</footer></section>}
    {screen === 'configure' && specialty && <section className="flow fade-in"><button className="back" onClick={() => setScreen('specialties')}>← All specialties</button><div className="flow-heading"><span className="eyebrow">OSCE CONFIGURATION</span><h1>{specialty.english}<small dir="rtl">{specialty.arabic}</small></h1><p>Select an examiner to begin a station from their historical case pool.</p></div><div className="choice-row"><button className={`mode-card ${mode === 'random' ? 'active' : ''}`} onClick={() => { setMode('random'); setExaminer(null); }}><i>✦</i><b>Random examiner</b><span>A realistic surprise, every time</span></button><button className={`mode-card ${mode === 'choose' ? 'active' : ''}`} onClick={() => setMode('choose')}><i>⌕</i><b>Choose examiner</b><span>Practice a specific physician</span></button></div>{mode === 'choose' && <div className="examiner-list">{availableExaminers.map((item) => <button key={item.id} className={`examiner-card ${examiner?.id === item.id ? 'selected' : ''}`} onClick={() => setExaminer(item)}><span className="doctor-avatar">{item.name.split(' ')[1][0]}{item.name.split(' ')[2]?.[0]}</span><span><b>{item.name}</b><small>{item.cases.length} available {item.cases.length === 1 ? 'case' : 'cases'} · {item.questions} historical questions</small></span><i>→</i></button>)}</div>}<div className="prep-panel"><div><span className="eyebrow">PREPARATION TIME</span><p>{loadingKnowledge ? 'Checking approved knowledge…' : publishedExaminers.length ? 'Using approved historical knowledge.' : 'Using development fixtures until approved knowledge is published.'}</p></div><div className="duration">{[3,4].map((item) => <button key={item} className={duration === item ? 'active' : ''} onClick={() => setDuration(item)}>{item} <small>min</small></button>)}</div><button className="start" disabled={loadingKnowledge || (mode === 'choose' && !examiner)} onClick={beginExam}>Start OSCE <span>→</span></button></div></section>}
    {screen === 'reveal' && examiner && <section className="reveal"><span className="eyebrow">YOUR EXAMINER</span><div className="examiner-reveal"><i>✚</i><h1>{examiner.name}</h1><p>{specialty?.english} · Historical OSCE station</p></div><span className="reveal-next">Preparing your station</span></section>}
    {screen === 'prepare' && examiner && caseStudy && <section className="station fade-in"><header className="station-head"><div className="brand"><i>✚</i><span>OSCE</span></div><div className="timer">{time}</div><div className="examiner-mini"><b>{examiner.name}</b><span>Examiner</span></div></header><div className="case-panel"><span className="eyebrow">YOUR CASE</span><h1>{caseStudy.title}</h1><div className="case-line"/><p>{caseStudy.scenario}</p><div className="station-actions"><button className="quiet-button" onClick={() => setScreen('question')}>Start exam now <span>→</span></button><span>Questions begin automatically when time ends.</span></div></div></section>}
    {screen === 'question' && examiner && caseStudy && currentQuestion && <section className="question-screen fade-in"><header className="question-head"><div><span className="eyebrow">QUESTION {questionIndex + 1} / {caseStudy.questions.length}</span><p>{examiner.name} <i>·</i> {caseStudy.title}</p></div><button className="end-link" onClick={() => setScreen('results')}>End station</button></header><article className="question-card"><span className="question-category">{currentQuestion.category}</span><h1>{currentQuestion.prompt}</h1><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Type your answer, or answer mentally…" aria-label="Your answer" /> {!revealed ? <><button className="reveal-button" disabled={evaluationState === 'submitting'} onClick={currentQuestion.evaluationReady ? submitEvaluation : () => setRevealed(true)}>{evaluationState === 'submitting' ? 'Evaluating…' : currentQuestion.evaluationReady ? 'Submit answer' : 'Show answer'}</button>{evaluationState === 'error' && <small>Evaluation could not be reached. Your answer is kept — <button className="end-link" onClick={submitEvaluation}>try again</button>.</small>}</> : evaluation ? <div className="answer-reveal"><span>Automatic evaluation</span><p>{evaluation.feedback}</p><small>Covered: {evaluation.coveredPoints.join(', ') || 'none'} · Missing: {evaluation.missingPoints.join(', ') || 'none'}</small><div className="grade-row"><button className="correct" onClick={() => grade(evaluation.correctness === 'CORRECT' ? 2 : evaluation.correctness === 'PARTIAL' ? 1 : 0, 'AUTOMATIC')}>Next question <span>→</span></button></div></div> : <div className="answer-reveal"><span>{evaluationState === 'fallback' ? 'Automatic evaluation unavailable — self-score' : currentQuestion.evaluationReady ? 'Evaluation-ready reference' : 'Expected answer'}</span><p>{currentQuestion.answer ?? 'No approved answer is available. Use self-scoring for this historical question.'}</p>{currentQuestion.explanation && <small>{currentQuestion.explanation}</small>}<div className="grade-row"><button onClick={() => grade(0)}>Incorrect</button><button onClick={() => grade(1)}>Partial</button><button className="correct" onClick={() => grade(2)}>Correct</button></div></div>}</article></section>}
    {screen === 'results' && <section className="results fade-in"><div className="result-card"><span className="eyebrow">OSCE COMPLETE</span><h1>Station<br/><em>complete.</em></h1><div className="result-score"><b>{scorePercent}%</b><span>overall score</span></div><div className="result-meta"><span><b>{examiner?.name}</b>Examiner</span><span><b>{caseStudy?.title}</b>Case</span><span><b>{scores.length}</b>Questions completed</span></div><div className="result-breakdown"><span><b>{scores.filter((score) => score === 2).length}</b> Correct</span><span><b>{scores.filter((score) => score === 1).length}</b> Partial</span><span><b>{scores.filter((score) => score === 0).length}</b> Incorrect</span><span><b>{scoreModes.filter((mode) => mode === 'AUTOMATIC').length}</b> Automatic</span><span><b>{scoreModes.filter((mode) => mode === 'SELF').length}</b> Self-scored</span></div><button className="start again" onClick={() => setScreen('specialties')}>Practice another station <span>→</span></button></div></section>}
  </main>;
}
